url: "https://cubedhs2017.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Douglas' Blog" # the name of your site, e.g. ACME Corp.


# markdown: kramdown
# highlighter: rouge

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge


